# Generated by Django 3.0 on 2022-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20220801_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='zodiacsign',
            field=models.CharField(choices=[(' Aries ', ' Aries '), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('leo', 'leo'), ('virgo', 'virgo'), ('libra', 'libra'), ('scorpio', 'scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], default=None, max_length=30),
        ),
    ]
