# Generated by Django 3.0 on 2022-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20220801_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zodiacsign',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
