# Generated by Django 3.0 on 2022-08-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20220801_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zodiacsign',
            field=models.CharField(default='zodiacsign', max_length=30),
        ),
    ]
