# Generated by Django 3.0 on 2022-08-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_auto_20220801_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zodiacsign',
        ),
    ]
