# Generated by Django 3.0 on 2022-08-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_user_zodiacsign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
