# Generated by Django 3.0 on 2022-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welcome', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('zodiac', models.CharField(default='name', max_length=30)),
            ],
        ),
    ]
